In [3]:
import numpy as np
import re
from itertools import groupby

In [2]:
#Q1. Write a program to check a year is a leap year or not.
#Input – Your program should take one year as input
#Output — Your program should print whether the year is or is not a leap year.

def leap_year_check(year):
    if (year%4 == 0) and ((year%400 == 0) or (year%100 != 0)):
        print('{} is a leap year'.format(year))
    else:
        print('{} is not a leap year'.format(year))
year = int(input('Enter the year to be checked:'))
leap_year_check(year)

Enter the year to be checked:2018
2018 is not a leap year


In [2]:
#Q2. The computer will pick a number between 1 and 100. (You can choose any high number you want.)
#The purpose of the game is to guess the number the computer picked in as few guesses as possible.
#Input – The user will enter his or her guess until the correct number is guessed.
#Output — The program will keep asking the user to guess until he or she gets the number correct.
#Then the program will print how many guesses were required.

flag = 0
count = 0 
actual_number = int(np.random.randint(1,100,1))
while(flag != 1):
    count = count+1
    number = int(input('Enter an integer of your choice to guess:'))
    if(number == actual_number):
        flag = 1
        print('Wohoo, you have guessed the number correctly!!')
    elif(number > actual_number):
        print('Lower your guess!')
    elif(number < actual_number):
        print('Raise your guess!')
print("You required {} guesses".format(count))

Enter an integer of your choice to guess:45
Lower your guess!
Enter an integer of your choice to guess:35
Raise your guess!
Enter an integer of your choice to guess:40
Lower your guess!
Enter an integer of your choice to guess:38
Lower your guess!
Enter an integer of your choice to guess:37
Lower your guess!
Enter an integer of your choice to guess:36
Wohoo, you have guessed the number correctly!!
You required 6 guesses


In [3]:
#Q3. What gets printed?
#def f() : pass
#print(type(f()))

#<class ‘function’>
#<class ‘tuple’>
#<class ‘NoneType’>
#<class ‘type’>


def f(): pass
print(type(f))

<class 'function'>


In [4]:
#Q4. What is the output for below programs?
#A = [1, 2, 3, None, (), [], ]
#print(len(A))
#Syntax error
#5
#6
#7

A = [1, 2, 3, None, (), [], ]
print(len(A))

6


In [19]:
#Q5. Write a program that calculates and prints the value according to the given formula:
#R = Square root of [(3 * A * C)/B]
#Following are the fixed values of A and B: A is 50. B is 30.
#C is the variable whose values should be input to your program in a comma-separated sequence.
#Input: 100, 150, 180
#Output: 18,22,24
a=50
b=30
r=0
output = []
c_input = list(input('Enter values of c:'))
c_list = ''.join(c_input).split(',')
for c in c_list:
    r = int(np.sqrt((3*a*int(c))/b))
    output.append(r)
print(output)

Enter values of c:100,150,180
[22, 27, 30]


In [5]:
#Q6. Write a program that accepts a sentence and calculate 
#the number of uppercase letters and lowercase letters.
#Input: Hello world!
#Output: Upper – 1, Lower – 9

sentence = input('Enter your sentence here:')
upper = [x for x in sentence if x.isupper()]
lower = [x for x in sentence if x.islower()]
print('Upper case characters in sentence:{}'.format(len(upper)))
print('Lower case characters in sentence:{}'.format(len(lower)))

Enter your sentence here:Hello world!
Upper case characters in sentence:1
Lower case characters in sentence:9


In [23]:
#Q7. Write a function in Python to test whether a number is prime or not.
#Input: 9
#Output: “Not Prime”

n = int(input("Please enter a number:"))
def is_prime(a):
    x = True
    for i in range(2, a):
            if a%i == 0:
                x = False
                break
            else:
                x = True
    if x:
        print("Prime")
    else:
        print ("Not Prime")
is_prime(n)

Please enter a number:23
Prime


In [40]:
#Q8. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 
#(both included) and the values are square of keys. The function should just print the keys only.

def dict_gene():
    keys = [x for x in range(1,21)]
    values = [key**2 for key in keys]
    dictionary = dict(zip(keys,values))
    print(dictionary.keys())
    print(dictionary.values())
    #return dictionary
dict_gene()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
dict_values([1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])


In [61]:
#Q9. Given a list of integers with duplicate elements in it. 
#The task to generate another list, which contains only the duplicate elements. 
#In simple words, the new list should contain the elements which appear more than one.
#Input: [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
#Output: [20, 30, -20, 60]

def duplicate(s):
    d_s = {x:s.count(x) for x in s}
    d_s_duplicates = [key for key in d_s.keys() if d_s[key]!=1]
    return d_s_duplicates
duplicate([10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20])

[20, 30, -20, 60]

In [3]:
#Q10. Write a Python Program to Count the Number of Vowels in a String?

string = input('Enter you string here:')
def vowel_count(s):
    count=0
    vowel = ['a','e','i','o','u']
    for x in ''.join(string.lower().split()):
        if x in vowel:
            count +=1
    return count
vowels = vowel_count(string)
print('No of vowels present:{}'.format(vowels))

Enter you string here:Hello World!
No of vowels present:3


In [2]:
#Q11. The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. 
#Find the sum of all the primes below one million.

n = int(input("Enter a number:"))
def is_prime(a):
    x = True
    for i in range(2, a):
            if a%i == 0:
                x = False
                break
            else:
                x = True
    return x

def sum_prime(b):
    sum=0
    prime_list = [prime for prime in range(2,b) if is_prime(prime)]
    for prime in prime_list:
        sum += prime
    return sum
sum_prime(n)

Enter a number:10


17

In [24]:
#Q12.  A palindrome number reads the same both ways. 
#The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
#Find the largest palindrome made from the product of two 3-digit numbers.


largest_pal = 0
for a in range(999, 99, -1):
    for b in range(a, 99, -1):
        prod = a * b
        if int(str(prod)[::-1]) == prod and prod > largest_pal:
            largest_pal = prod

print(largest_pal)

906609


In [7]:
#Q13. You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.
#Input: ‘PytHoN’
#Output: ‘pYThOn’

string = input('Enter the string for case conversion:')
result = ''.join([x.lower() if x.isupper() else x.upper() for x in ''.join(string.split())])
print(result)

Enter the string for case conversion:PytHoN
pYThOn


In [28]:
#Q14. Find the second smallest element in a list without using any predefined sort function.
#Note- Try to solve the same in a single iteration.

inp = input('Enter a list of comma-separated numbers:')
l = inp.split(',')
l =[int(x) for x in l]
print(l)
def second_smallest(numbers):
    m1, m2 = numbers[0], numbers[0]
    for x in numbers:
        if x <= m1:
            m1, m2 = x, m1
        elif x < m2:
            m2 = x
    return m2
second_lowest = second_smallest(l)
print(second_lowest)
print(sorted(l)[1])

Enter a list of comma-separated numbers:5,6,4,7,3,8
[5, 6, 4, 7, 3, 8]
4
4


In [9]:
#Q15. If we have some email addresses in the “username@companyname.com” format, 
#please write a program to print the username of a given email address.
#Both usernames and company names are composed of letters only.

email = input('Enter your mail id here:')
username = email.split('@')[0]
print(username)

Enter your mail id here:abcd@gmail.com
abcd


In [14]:
#Q16. You are working with a banking firm where your job is to verify credit card numbers. 
#A valid credit card has the following characteristics –
#It must start with 4, 5, 6.
#It must contain exactly 16 characters.
#It must only consist of digits (0-9).
#It may have digits in groups of, separated by one hyphen “-“.
#It must NOT use any other separator like ‘ ‘ , ‘_’, etc.
#It must NOT have or more consecutive repeated digits
#Input: 42536258796157867
#Output: INVALID
i=5
def count_consecutive(num):
    return max(len(list(g)) for _, g in groupby(num))
               
def credit_card_validation(card_number):
    pattern1 = re.match('456[0-9]{12}',card_number)
    pattern2 = re.match('456[0-9]{1}\-(?:\d{4}-?){2}\d{4}',card_number)
    if ((pattern1 and len(card_number)==16) or (pattern2 and len(card_number)==19)) and (count_consecutive(card_number.replace('-', '')) < 4):
        print('VALID')
    else:
        print('INVALID')
while(i!=0):  
    i -= 1
    num = input('Enter 16 digit credit card number:')
    credit_card_validation(num)

Enter 16 digit credit card number:42536258796157867
INVALID
Enter 16 digit credit card number:4563-6258-7961-5786
VALID
Enter 16 digit credit card number:45636-258-7961-5786
INVALID
Enter 16 digit credit card number:4566-6658-7961-5786
INVALID
Enter 16 digit credit card number:4563625879615786
VALID


In [16]:
#Q17. Find the smallest number which is divisible by all the numbers between 1 to 15.

from math import gcd
a = [x for x in range(1,16)]
lcm = a[0]
for i in a[1:]:
     lcm = int(lcm*i/gcd(lcm, i))
print(lcm)

360360


In [57]:
#Q18. Write a program to add two 3×3 matrices using the nested loop.
#Note- try the same program using Numpy array.
print('Using nested loop:')
m1 = [[1,2,3],[4,5,6],[7,8,9]]
m2=[[9,8,7],[6,5,4],[3,2,1]]
print(m1)
print(m2)
for i in range(len(m1)):
    for j in range(len(m1)):
        m1[i][j] = m1[i][j] + m2[i][j]
print('\n')
print('Result:')
print(m1)

print('\n')
print('Using Numpy Array:')
m_np1 = np.random.randint(0,10,(3,3))
m_np2 = np.random.randint(10,20,(3,3))
print(m_np1)
print('\n')
print(m_np2)
print('\n')
print('Result:')
print(m_np1+m_np2)

Using nested loop:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


Result:
[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


Using Numpy Array:
[[5 0 6]
 [1 5 0]
 [1 1 8]]


[[18 18 17]
 [12 17 17]
 [17 12 19]]


Result:
[[23 18 23]
 [13 22 17]
 [18 13 27]]
