In [1]:
import numpy as np

In [5]:
#Q1. Write a program which takes 2 digits, X, Y as input and generates a 2-dimensional array. 
#The element value in the i-th row and j-th column of the array should be i*j.
#Note: i = 0,1.., X-1;   j=0,1,¡Y-1.

#Input – 3,5
#Output – [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

rows = int(input('Enter no of rows:'))
cols = int(input('Enter no of columns:'))
def array_build(x,y):
    array = np.empty((x,y))
    for i in range(0,rows):
        for j in range(0,cols):
            array[i,j] = i*j
    print(array)
array_build(rows,cols)

Enter no of rows:3
Enter no of columns:5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [8]:
#Q2. Write a program that accepts the sequence of lines as input and prints the lines after making 
#all characters in the sentence capitalized.

#Input:
#Hello world
#Practice makes perfect
#Output:
#HELLO WORLD
#PRACTICE MAKES PERFECT

sequences = input('Enter the sentences:')
def capitalize(s):
    s = s.split('.')
    for sentence in s:
        capital = ''.join([word.upper() for word in sentence])
        print(capital)
capitalize(sequences)

Enter the sentences:Hello world.Practice makes perfect.
HELLO WORLD
PRACTICE MAKES PERFECT



In [14]:
#Q3. Write a program using a generator to print the numbers which can be divisible by 5 and 7 
#between 0 and n in comma separated form while n is input by a console.

number = int(input('Enter a number:'))
def div_5_7(n):
    num_list = [num for num in range(1,n) if (num%5==0 and num%7==0)]
    print(num_list)
div_5_7(number)

Enter a number:100
[35, 70]


In [21]:
#Q4. Write a program which accepts a string from console and print the characters
#that have even indexes.
#Input: “H1e2l3l4o5w6o7r8l9d”
#Output: “Helloworld”

string = input('Enter a string:')
def even_indices(s):
    even_char = ''.join([s[i] for i in range(0,len(s),2)])
    print(even_char)
even_indices(string)

Enter a string:H1e2l3l4o5w6o7r8l9d
Helloworld


In [49]:
#Q5. Given a string, find the length of the longest substring without repeating characters.

#Input: “pwwkew”
#Output: 3
#Explanation: The answer is “wke”, with the length of 3. 
#Note that the answer must be a substring, “pwke” is a subsequence and not a substring.

def substring(s):
    sub_str =[]
    sub_strings={}
    for char in s:
        if char not in sub_str:
            sub_str.append(char)
        else:
            sub_strings[''.join(sub_str)] = len(sub_str)
            sub_str = []
            sub_str.append(char)
    print(max(sub_strings.items())[1])
substring('pwwkew')

3


In [4]:
#Q6. Given an integer, convert it to a roman numeral. 
#Input is guaranteed to be within the range from 1 to 3999.

#Input: 1994
#Output: “MCMXCIV”
#Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.

import math 
def integerToRoman(A): 
    roman =  { 1: "I", 5: "V", 10: "X", 50: "L", 100: "C", 500: "D", 1000: "M", 5000: "G", 10000: "H"} 
    div = 1
    while A >= div: 
        div *= 10
  
    div /= 10
  
    res = "" 
  
    while A:   
        lastNum = int(A / div) 
        if lastNum <= 3: 
            res += (roman[div] * lastNum) 
        elif lastNum == 4: 
            res += (roman[div] + roman[div * 5]) 
        elif 5 <= lastNum <= 8: 
            res += (roman[div * 5] + (roman[div] * (lastNum - 5))) 
        elif lastNum == 9: 
            res += (roman[div] + roman[div * 10]) 
        A = math.floor(A % div) 
        div /= 10
          
    return res 
print(integerToRoman(1994))

MCMXCIV


In [26]:
#Q7. Given a string s of length at most 10,000 letters. 
#Create a dictionary with the number of occurrences of each word in s as values, 
#where words are separated by spaces. Words are case-sensitive, and the lines in the output can be 
#in any order.
#Input: “We tried list and we tried dicts also we tried Zen”
#Output: {‘and’: 1, ‘We’: 1, ‘tried’: 3, ‘dicts’: 1, ‘list’: 1, ‘we’: 2, ‘also’: 1, ‘Zen’: 1}
import nltk
#nltk.download('gutenberg');
#nltk.download('genesis');
#nltk.download('inaugural');
#nltk.download('nps_chat') ;
#nltk.download('webtext');
#nltk.download('treebank');
from nltk.book import *
s = input('Enter text here:')
fdist = FreqDist(s.split())
print(fdist.most_common())

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908
Enter text here:We tried list and we tried dicts also we tried Zen
[('tried', 3), ('we', 2), ('We', 1), ('list', 1), ('and', 1), ('dicts', 1), ('also', 1), ('Zen', 1)]


In [69]:
#Q8. Given two strings s and t of equal length. Find the Hamming distance between s and t, 
#denoted by dH(s,t), which is the number of corresponding symbols that differ in s and t.
#Input: s – “GAGCCTACTAACGGGAT”
#t – “CATCGTAATGACGGCCT”
#Output: 7
strings = input('Enter 2 strings of equal length(comma separated):')
def hamming(string):
    count=0
    s = string.split(',')[0]
    t = string.split(',')[1]
    if len(s) == len(t):
        for i in range(len(s)):
            if s[i] != t[i]:
                count+=1
    return count
distance = hamming(strings)
print(distance)

Enter 2 strings of equal length(comma separated):GAGCCTACTAACGGGAT,CATCGTAATGACGGCCT
7


In [74]:
#Q9. Given two integers dividend and divisor, divide two integers without using multiplication, 
#division and mod operator. Return the quotient after dividing dividend by divisor.
#Note- The integer division should truncate toward zero.
#Input: dividend = 10, divisor = 3
#Output: 3

def division(dividend,divisor):
    quotient = 0
    while(dividend>=divisor):
        dividend-=divisor
        quotient+=1
    return quotient
result = division(10,3)
result

3

In [18]:
#Q10. Given a collection of distinct integers, return all possible permutations.
#Input: [1,2,3]
#Output: [[1,2,3], [1,3,2], [2,1,3], [2,3,1], [3,1,2], [3,2,1]]

from itertools import permutations
l = list(permutations([1,2,3]))
print(l)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [76]:
#Q11. Write a function to count the number of prime numbers less than a non-negative number, n.
#Input: 10
#Output: 4
#Explanation: There are 4 prime numbers less than 10, they are 2, 3, 5, 7.

n = int(input("Enter a number:"))
def is_prime(a):
    x = True
    for i in range(2, a):
            if a%i == 0:
                x = False
                break
            else:
                x = True
    return x

def count_prime(b):
    sum=0
    prime_list = [prime for prime in range(2,b) if is_prime(prime)]
    return len(prime_list)
count = count_prime(n)
print('Number of prime numbers below {} is: {}'.format(n,count))

Enter a number:10
Number of prime numbers below 10 is: 4


In [107]:
#Q12. Given a string which contains only lowercase letters, remove duplicate letters 
#so that every letter appears once and only once. You must make sure your result is the smallest
#in lexicographical order among all possible results.
#Input: “cbacdcbc”
#Output: “acdb”

string = input('Enter string here:')
letters = sorted(string)
lexico_order=[]
for char in letters:
    if char not in lexico_order:
        lexico_order.append(char) 
print(lexico_order)

Enter string here:cbacdcbc
['a', 'b', 'c', 'd']


In [27]:
#Q13. Write a function FirstFactorial (num) take the num parameter being passed and return the 
#factorial of it. For example: if num = 4, then your program should return (4 * 3 * 2 * 1) = 24.
#Also, write an error catch statement to make sure the input value is a number.


def FirstFactorial():
    factorial = 1
    try:
        num = int(input('Enter a number:'))
        if num == 0 :
            print('1')
        elif num < 0:
            print('Factorial does not exist')
        else:
            for i in range(1,num+1):
                factorial = factorial*i
            print(factorial) 
    except ValueError:
        print('Input is invalid.Please enter an integer!')
FirstFactorial()

Enter a number:4
24


In [25]:
#Q14. Given an integer ‘n’, generate the first ‘n’ terms of the Connell Sequence.
#Connell Sequence is the sequence formed with the first odd number, i.e 1 as its first term. 
#The subsequent terms of the sequence are made up of the first two even numbers, i.e 2 and 4,
#followed by the next three odd numbers, i.e 5, 7 and 9, followed by the next four even numbers, 
#i.e 10, 12, 14 and 16 and so on …. the sequence continues.

def connell_seq(n):
    connell = [1]
    i=1
    end_term = 0
    while(i!=0):
        i+=1
        if(i%2 == 0):
            end_term = i**2
            even=[]
            while(end_term > (i-1)**2):
                connell.append(end_term)
                end_term -= 2
        if(i%2 == 1):
            end_term = i**2
            odd=[]
            while(end_term > (i-1)**2):
                connell.append(end_term)
                end_term -= 2
        if len(connell)>n:
            i=0
            print(sorted(connell[:n]))
connell_seq(12)

[1, 2, 4, 5, 7, 9, 10, 12, 14, 16, 23, 25]


In [16]:
#Q16. Rohit recently made a robot which reduces his effort to move things. The robot moves from 
#one place to another in a straight line to move things, but it has got a bug in it.
#After moving Y meters forward, it comes back X meters. Now Rohit wants to know how much 
#total distance the robot covers if it needs to reach Z meters from the starting point. 
#Help him find this. It is guaranteed that the robot will reach its destination.

#Input: Y- 5, X- 2, Z- 9
#Output: 17

def total_dist(y,x,z):
    total=0
    location=0
    step=0
    while(location<z):
        location = location + y - x
        total = total+x+y
        if location>=z-y:
            step = z-location 
            total = total + step
            location = location+step
    print(total)
total_dist(5,2,9)

17


In [20]:
#Q18. 145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145. Find the sum of all numbers 
#(below 50,000) which are equal to the sum of the factorial of their digits.
#Note: as 1! = 1 and 2! = 2 are not sums they are not included.
from math import factorial
def fact_sum(numrange):
    factsum=0
    for num in range(10,numrange):
        sum1=0
        temp=num
        while(num):
            f=1
            r=num%10
            f = factorial(r)
            sum1=sum1+f
            num=num//10
        if(sum1==temp):
            factsum += sum1
    print(factsum)
fact_sum(50000)

40730
